// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yhkbzsnflnylnsnmucxg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inloa2J6c25mbG55bG5zbm11Y3hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTMxMzMsImV4cCI6MjA2OTYyOTEzM30._6Exb2f0W808f-BEX1Qf4FeR3r1PuqwNqHlRqCfmrRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});